import {Router} from "express";
import auth from "../middleware/authMiddleware.js";
import {roles} from "../middleware/roleMiddleware.js";
import {list,create,me,updateMe,updateByAdmin,importCsv} from "../controllers/studentController.js";
import {uploadCsv} from "../middleware/uploadMiddleware.js";
const r=Router();
r.use(auth);
r.get("/me",roles("student"),me);
r.put("/me",roles("student"),updateMe);
r.get("/",roles("admin"),list);
r.post("/",roles("admin"),create);
r.post("/import",roles("admin"),uploadCsv.single("file"),importCsv);
r.put("/:id",roles("admin"),updateByAdmin);
export default r;
