import React,{useState} from "react";
import api from "../services/api";
import {pick} from "../utils/normalize";
function initials(name=""){return name.split(" ").filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()).join("")||"?";}
export default function CandidateCard({candidate,onSaved}){
 const [editing,setEditing]=useState(false); const [busy,setBusy]=useState(false); const [form,setForm]=useState({name:candidate.name||"",branch:candidate.branch||"",course:candidate.course||"",cgpa:candidate.cgpa??"",backlogs:candidate.backlogs??0,graduationYear:candidate.graduationYear??"",skills:(candidate.skills||[]).join(", "),experienceMonths:candidate.experienceMonths??0});
 const name=pick(candidate,["name","fullName"],"Unnamed candidate");
 async function save(){setBusy(true);try{const {data}=await api.put(`/students/${candidate._id}`,{...form,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean)});setEditing(false);onSaved?.(data)}catch(e){alert(e.response?.data?.message||e.message)}finally{setBusy(false)}}
 if(editing)return <div className="candidate-card"><h4>Edit candidate</h4><div className="auth-grid"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name"/><input value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})} placeholder="Branch"/></div><div className="auth-grid"><input value={form.course} onChange={e=>setForm({...form,course:e.target.value})} placeholder="Course"/><input type="number" step="0.01" value={form.cgpa} onChange={e=>setForm({...form,cgpa:e.target.value})} placeholder="CGPA"/></div><div className="auth-grid"><input type="number" value={form.backlogs} onChange={e=>setForm({...form,backlogs:e.target.value})} placeholder="Backlogs"/><input type="number" value={form.experienceMonths} onChange={e=>setForm({...form,experienceMonths:e.target.value})} placeholder="Experience months"/></div><input value={form.graduationYear} onChange={e=>setForm({...form,graduationYear:e.target.value})} placeholder="Graduation year"/><input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Skills: React, SQL, DSA"/><div style={{display:"flex",gap:8}}><button className="btn" onClick={save} disabled={busy}>{busy?"Saving…":"Save"}</button><button className="btn-ghost btn" onClick={()=>setEditing(false)}>Cancel</button></div></div>;
 return <div className="candidate-card" style={{"--accent":"var(--sky)"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><div className="avatar">{initials(name)}</div><div><b>{name}</b><small>{candidate.branch||"—"} · CGPA {candidate.cgpa??"—"}</small><small>{candidate.skills?.join(", ")||"No skills"}</small></div></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12}}><span className="score">{candidate.readinessScore!=null?`${candidate.readinessScore}%`:"—"}</span><button className="btn-ghost btn" onClick={()=>setEditing(true)}>Edit profile</button></div></div>;
}
