import React, { useEffect, useState } from "react";
import api from "../services/api";
import PageHeader from "../components/PageHeader";
import { useAuth } from "../context/AuthContext";

export default function Profile(){
  const {user}=useAuth();
  const [form,setForm]=useState({name:"",phone:"",branch:"",course:"",cgpa:"",backlogs:0,graduationYear:"",skills:"",experienceMonths:0,experienceDetails:"",certifications:"",preferredLocations:""});
  const [placementStatus,setPlacementStatus]=useState("");
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [message,setMessage]=useState(""), [error,setError]=useState("");
  useEffect(()=>{api.get("/students/me").then(({data})=>{setForm({name:data.name||"",phone:data.phone||"",branch:data.branch||"",course:data.course||"",cgpa:data.cgpa??"",backlogs:data.backlogs??0,graduationYear:data.graduationYear??"",skills:(data.skills||[]).join(", "),experienceMonths:data.experienceMonths??0,experienceDetails:data.experienceDetails||"",certifications:(data.certifications||[]).join(", "),preferredLocations:(data.preferredLocations||[]).join(", ")});setPlacementStatus(data.placementStatus||"");}).catch(e=>setError(e.response?.data?.message||e.message)).finally(()=>setLoading(false));},[]);
  const set=(k)=>(e)=>setForm(v=>({...v,[k]:e.target.value}));
  async function save(e){e.preventDefault();setSaving(true);setMessage("");setError("");try{const {data}=await api.put("/students/me",{...form,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),certifications:form.certifications.split(",").map(x=>x.trim()).filter(Boolean),preferredLocations:form.preferredLocations.split(",").map(x=>x.trim()).filter(Boolean)});setForm(v=>({...v,skills:(data.skills||[]).join(", ")}));setMessage("Profile updated. Your eligibility and match scores for every open job have been refreshed.");}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
  if(loading)return <section className="page"><p>Loading profile…</p></section>;
  return <section className="page"><PageHeader eyebrow="Student profile" title="Edit your placement profile" description="Change skills and every placement criterion. The AI pipeline uses these values when evaluating jobs."/>
  {placementStatus==="Selected"&&<div className="panel" style={{borderColor:"#A7F3D0",marginBottom:14}}>🎉 <b>Selected!</b> Congratulations — check your Interviews page for details.</div>}
  {placementStatus==="In Process"&&<div className="panel" style={{marginBottom:14}}>Placement status: <b>Interview in process</b></div>}
  {placementStatus==="Not Selected"&&<div className="panel" style={{marginBottom:14}}>Placement status: <b>Not selected</b> this time — check your Skill Gap page for what to build next.</div>}
  {error&&<div className="panel error">{error}</div>}{message&&<div className="panel" style={{borderColor:"#A7F3D0"}}>{message}</div>}<form onSubmit={save} className="panel" style={{display:"grid",gap:14}}><div className="auth-grid"><label>Full name<input value={form.name} onChange={set("name")}/></label><label>Phone<input value={form.phone} onChange={set("phone")}/></label></div><div className="auth-grid"><label>Branch<input value={form.branch} onChange={set("branch")}/></label><label>Course<input value={form.course} onChange={set("course")}/></label></div><div className="auth-grid"><label>CGPA<input type="number" min="0" max="10" step="0.01" value={form.cgpa} onChange={set("cgpa")}/></label><label>Backlogs<input type="number" min="0" value={form.backlogs} onChange={set("backlogs")}/></label></div><div className="auth-grid"><label>Graduation year<input type="number" value={form.graduationYear} onChange={set("graduationYear")}/></label><label>Experience (months)<input type="number" min="0" value={form.experienceMonths} onChange={set("experienceMonths")}/></label></div><label>Skills <span className="muted">comma separated; e.g. MERN, SQL, DSA</span><input value={form.skills} onChange={set("skills")}/></label><label>Experience details<textarea rows="3" value={form.experienceDetails} onChange={set("experienceDetails")}/></label><label>Certifications <span className="muted">comma separated</span><input value={form.certifications} onChange={set("certifications")}/></label><label>Preferred locations <span className="muted">comma separated</span><input value={form.preferredLocations} onChange={set("preferredLocations")}/></label><button className="auth-submit" disabled={saving}>{saving?"Saving…":"Save profile"}</button></form></section>;
}
